const actionType = {
  GET_HOME: "GET_HOME",
  SET_CUR_SONG_ID: "SET_CUR_SONG_ID",
  CHANGE_ISPLAING: "CHANGE_ISPLAING",
  ADD_SONGS: "ADD_SONGS",
  ADD_SONG: "ADD_SONG",
  REMOTE_SONGS: "REMOTE_ALBUM",
  REMOTE_SONG: "REMOTE_SONG",
  SET_ALBUM: "SET_ALBUM",
  GET_PLAYLIST: "GET_PLAYLIST"
};

export default actionType;
